before_build:
  - dotnet restore --verbosity Error
  - dotnet gitversion
pull_requests:
  do_not_increment_build_number: true

test: off  

build:
  project: Build\EasyNetQ.proj
  verbosity: minimal
  publish_nuget: false

branches:
  only:
  - appveyorTest

artifacts:
  - path: Package\**\*.nupkg

deploy:
  - provider: NuGet
    artifact: /.*\.nupkg/
    server: https://www.myget.org/F/easynetq-test1/api/v2/package
    api_key:
      secure: test
    on:
      branch: master
  - provider: NuGet
    artifact: /.*\.nupkg/
    server: https://www.myget.org/F/easynetq-test1/api/v2/package
    api_key:
       secure: NulQ1qClvThpFTs6XZfer2DG8Qe2TjK0bt1zhAuvRXe9opfwJIbAEMr1ceUl/N79
    on:
      branch: appveyorTest

skip_commits:
  files:
  - .gitattributes
  - .gitignore
  - README.md
  - build.bat
  - hall_of_fame.md
  - licence.txt
  - DatabaseScripts/*
